#ifndef __t186ref_build_t186_user_tasks_nvidia_sample_luks_srv_config_h_H
#define __t186ref_build_t186_user_tasks_nvidia_sample_luks_srv_config_h_H
#define USER_TASK 1
#define OPENSSL_SYS_TRUSTY
#define USER_TASK_WITH_APP_TRUSTY 1
#define USER_TASK_WITH_INTERFACE_HWRNG 1
#define USER_TASK_WITH_LIB_LIBC 1
#define USER_TASK_WITH_LIB_LIBC_TRUSTY 1
#define USER_TASK_WITH_LIB_OPENSSL 1
#define USER_TASK_WITH_LIB_OPENSSL_STUBS 1
#define USER_TASK_WITH_LIB_RNG 1
#endif
